name: 'CI'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    if: ${{ contains(github.actor, 'dependabot') != true }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3.2.2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test

      - name: Check code with PHP Inshights
        run: vendor/bin/phpinsights -n --ansi --format=github-action

      - name: Check code with PHP Stan
        run: vendor/bin/phpstan --error-format=github

      - name: Check for ray calls
        run: ./vendor/bin/x-ray src --github

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3.13.0
        if: failure()
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format files
        run: ./vendor/bin/php-cs-fixer fix

      - name: Commit files to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: cs_fixer applied"
          commit_user_name: "Query Builder Filters GitHub Actions Bot"
          commit_user_email: "query-builder-filters@rywal.dev"
          commit_author: "Query Builder Filters GitHub Actions Bot <query-builder-filters@rywal.dev>"

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3.13.0
        if: success()
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
